---
title: "[PSYCH 260](https://psu-psychology.github.io/psych-260-2020-fall)"
subtitle: "Exam 1 Review"
author: "Rick Gilmore"
date: "`r Sys.time()`"
bibliography: bib/psych260.bib
csl: bib/apa.csl
output:
  ioslides_presentation:
    css: css/ioslides.css
    incremental: no
    transition: default
    widescreen: yes
  pdf_document:
    latex_engine: xelatex
---

## Methods

- [Spatial & temporal resolution](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-08-27-history-levels-methods.html#25)
    - Spatial--microscope (high/fine resolution) vs. telescope (low/poor)
    - Temporal--stopwatch (high/fine) vs. calendar (low/poor)
- [Structural vs. functional](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-08-27-history-levels-methods.html#39)
- Invasive vs. non-invasive

## Methods (continued)

- MRI 
    - [structural](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-08-27-history-levels-methods.html#54)
    - [diffusion tensor imaging-DTI](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-08-27-history-levels-methods.html#59)
    - [functional MRI-fMRI](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-01-methods.html#42)
- [CT](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-08-27-history-levels-methods.html#50)
- [EEG](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-01-methods.html#47), [MEG](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-01-methods.html#54), & [ERP](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-01-methods.html#51)
- [Stimulation (chemical, electrical, magnetic, optical)](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-01-methods.html#57)

## Neuroanatomy

- [Directions](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-03-anatomy-I.html#32) & [slices](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-03-anatomy-I.html#35)
- [Hindbrain, midbrain, forebrain & ventricular landmarks](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-03-anatomy-I.html#49)
- [Meninges](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-03-anatomy-I.html#37)
- [Lobes of the cerebral cortex](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-08-anatomy-II.html#43) & [components](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-08-anatomy-II.html#54) & [lobes/landmarks/areas](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-08-anatomy-II.html#74)
- [Fissures & sulci](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-08-anatomy-II.html#46)

## Neuroanatomy

- [CNS vs. PNS](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-03-anatomy-I.html#48)
- [Autonomic vs. somatic](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-08-anatomy-II.html#85) parts of PNS
- [Sympathetic vs. parasympathetic divisions](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-08-anatomy-II.html#88) of the Autonomic Nervous System

## Cellular neuroscience

- [Glia](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-15-cells.html#14)
- [Neuronal anatomy](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-15-cells.html#26)
- [Resting potential -- what is it & why does it occur](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-15-cells.html#49)
    - [$[K^+]$ story](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-22-cells-III.html#8) (where concentrated, direction of flow)
    + [$[Na^+]$ story0(https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-22-cells-III.html#12) (where concentrated, direction of flow)
- [Action potential and propagation -- how & why](https://psu-psychology.github.io/psych-260-2020-fall/lectures/260-2020-09-17-cells-II.html#39)
